org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# Proje yolu "Masaüstü" gibi ASCII olmayan karakter içerdiği için Android Gradle
# Plugin'in path kontrolünü devre dışı bırakıyoruz (bkz. http://b.android.com/95744).
android.overridePathCheck=true
